AWSTemplateFormatVersion: 2010-09-09
Description: CI/CD pipeline for GitHub projects
Resources:
  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://test-pipeliene-cloudformation.s3.amazonaws.com/CodeBuildServiceRole.yml
        


        
