AWSTemplateFormatVersion: 2010-09-09
Description: CI/CD pipeline for GitHub projects
Parameters:
  CodeBuildEnvironmentImage:
    Type: String
    Default: 'aws/codebuild/standard:4.0'
Resources:
  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://github.com/JulianPiedrahita/Credicorp/blob/main/Templates_pipeline/CodeBuildServiceRole.yml

        


        
