AWSTemplateFormatVersion: 2010-09-09
Resources: 
  CodeBuildServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Policies:
        - PolicyName: devops
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: ModifyBucketPolicy
                Effect: Allow
                Action:
                  - 's3:GetBucketPolicy'
                  - 's3:PutBucketPolicy'               
                Resource:
                  - 'arn:aws:s3:::*'
              - Sid: AccessS3Console
                Effect: Allow
                Action:
                  - 's3:GetBucketLocation'
                  - 's3:ListAllMyBucke'               
                Resource:
                  - 'arn:aws:s3:::*'
              - Sid: S3GetObjectPolicy
                Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                Resource:
                  - '*'
              - Sid: S3PutObjectPolicy
                Effect: Allow
                Action:
                  - 's3:PutObject'
                Resource:
                  - '*'
              - Sid: S3BucketIdentity
                Effect: Allow
                Action:
                  - 's3:GetBucketAcl'
                  - 's3:GetBucketLocation'
                Resource:
                  - '*'
Outputs:
  CodeBuildServiceRole:
    Value: !Ref CodeBuildServiceRole




