AWSTemplateFormatVersion: 2010-09-09



Resources: 
  CodeBuildServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: devops
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowUserToPassRole
                Effect: Allow
                Action:
                  - 'iam:AttachGroupPolicy'
                  - 'iam:AttachUserPolicy'
                  - 'iam:CreatePolicy'
                  - 'iam:ListAttachedGroupPolicies'
                  - 'iam:ListAttachedUserPolicies'
                  - 'iam:ListGroups'
                  - 'iam:ListPolicies'
                  - 'iam:ListUsers'
                  - 'iam:GetRole'
                  - 'iam:PassRole'
                  - 'iam:AddRoleToInstanceProfile'
                  - 'iam:AttachRolePolicy'
                  - 'iam:CreateInstanceProfile'
                  - 'iam:CreatePolicy'
                  - 'iam:CreateRole'
                  - 'iam:GetRole'
                  - 'iam:ListAttachedRolePolicies'
                  - 'iam:ListPolicies'
                  - 'iam:ListRoles'
                  - 'iam:PutRolePolicy'
                  - 'iam:UpdateAssumeRolePolicy'
                  - 'rds:DescribeDBClusters'
                  - 'rds:DescribeDBInstances'
                  - 'redshift:DescribeClusters'
                Resource:
                  - '*'
              - Sid: AllowUserToGeneratePolicy
                Effect: Allow
                Action:
                  - 'access-analyzer:CancelPolicyGeneration'
                  - 'access-analyzer:GetGeneratedPolicy'
                  - 'access-analyzer:ListPolicyGenerations'
                  - 'access-analyzer:StartPolicyGeneration'
                  - 'access-analyzer:ValidatePolicy'
                  - 'access-analyzer:CreateAnalyzer'
                Resource:
                  - '*'
              - Sid: SecretsManagePolicy
                Effect: Allow
                Action:
                  - 'secretsmanager:GetResourcePolicy'
                  - 'secretsmanager:GetSecretValue'
                  - 'secretsmanager:DescribeSecret'
                  - 'secretsmanager:ListSecretVersionIds'
                  - 'secretsmanager:CreateSecret'
                  - 'secretsmanager:ListS'
                Resource:
                  - '*'       
              - Sid: CloudWatchLogsPolicy
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - '*'
              - Sid: S3GetObjectPolicy
                Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                Resource:
                  - '*'
              - Sid: S3PutObjectPolicy
                Effect: Allow
                Action:
                  - 's3:PutObject'
                Resource:
                  - '*'
              - Sid: S3BucketIdentity
                Effect: Allow
                Action:
                  - 's3:GetBucketAcl'
                  - 's3:GetBucketLocation'
                Resource:
                  - '*'





