name: Upload S3 

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Connect to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        token: ${{ secrets.TOKEN_GITHUB }}
        aws-region: ${{ secrets.REGION }}

    - name: Upload Dir to S3 -source
      run: aws s3 sync ./ s3://test-pipeliene-cloudformation/templates_pipeline --exclude='node_modules/' --exclude='.git/'
      env:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

       

    