name: Upload S3 test.

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Connect to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        token: ${{ secrets.TOKEN_GITHUB }}
        aws-region: ${{ secrets.REGION }}

    - name: Deploy to S3 bucket
      run: aws s3 sync ./public/ s3://${{ secrets.AWS_S3_BUCKET }} --delete    